services:
  # 1. VERİTABANI SERVİSİ
  mysqldb:
    image: mysql:8.0
    container_name: library_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db_v2
    ports:
      - "3306:3306"
    volumes:
      # DÜZELTME: Klasör yerine Volume kullanıyoruz ve ismini değiştirdik.
      # Bu sayede Docker eski bozuk veriyi bulamayıp mecburen sıfırdan kuracak.
      - mysql_data_FINAL_FIX:/var/lib/mysql
    networks:
      - library-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. BACKEND SERVİSİ
  backend:
    build: ./backend
    container_name: library_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/library_db_v2?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - library-network
    depends_on:
      mysqldb:
        condition: service_healthy

  # 3. FRONTEND SERVİSİ
  frontend:
    build: ./frontend
    container_name: library_frontend
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true 
    stdin_open: true
    tty: true
    networks:
      - library-network
    depends_on:
      - backend

# AĞ AYARLARI
networks:
  library-network:
    driver: bridge

# VOLUME AYARLARI (YENİ)
volumes:
  mysql_data_FINAL_FIX:
    driver: local