version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: library_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db_v2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - library-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db-data: {}

networks:
  library-network:
    driver: bridge